apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapp
  labels:
    app: helloworldapp
spec:
  selector:
    matchLabels:
      app: helloworldapp
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworldapp
    spec:
      containers:
      - name: app
        image: networkingcat/hello_world
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: VERSION_INFO
          value: "VERSION_INFO_VALUE"
        - name: BUILD_DATE
          value: "BUILD_DATE_VALUE"
        ports:
        - containerPort: 80
