# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2.1

# Use circleci orbs for easy use
orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.0
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies- 
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint


#
# Maybe try remote docker later, need to manually copy files
#
#  docker_stuff:
#    docker:
#      - image: python:3.7.3-stretch  
#    working_directory: ~/app
#    resource_class: small       
#    steps:
#      - checkout
#      - setup_remote_docker:
#          version: 19.03.13
#      - run:
#          name: Build docker image and upload
#          command: |
#            docker login -u networkingcat -p ${DOCKER_PWD}
#            docker build -t networkingcat/hello_world:${CIRCLE_BUILD_NUM} .
#            docker push networkingcat/hello_world:${CIRCLE_BUILD_NUM}
#            docker tag networkingcat/hello_world:${CIRCLE_BUILD_NUM} networkingcat/hello_world:latest
#            docker push networkingcat/hello_world:latest



  docker_stuff:
    machine: true
    working_directory: ~/app
    resource_class: medium       
    steps:
      - checkout
      - run:
          name: Build docker image and upload to dockerhub
          command: |
            # unsecure, do not use
            # docker login -u networkingcat -p ${DOCKER_PASSWORD}
            echo $DOCKER_PASSWORD | docker login -u networkingcat --password-stdin
            docker build -t networkingcat/hello_world:${CIRCLE_BUILD_NUM} .
            docker push networkingcat/hello_world:${CIRCLE_BUILD_NUM}
            docker tag networkingcat/hello_world:${CIRCLE_BUILD_NUM} networkingcat/hello_world:latest
            docker push networkingcat/hello_world:latest


  create_services:
    executor: aws-eks/python3
    resource_class: small    
    parameters:
      cluster-name:
        description: |
          cluster name
        type: string
      aws-region:
        type: string     
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: eu-central-1
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: app-deployment.yml
          resource-name: deployment/helloworldapp
      - kubernetes/create-or-update-resource:
          resource-file-path: app-service.yaml


  collect_info:
    executor: aws-eks/python3
    resource_class: small    
    parameters:
      cluster-name:
        description: |
          cluster name
        type: string
      aws-region:
        type: string           
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: eu-central-1
      - run:
          name: show info
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
            kubectl get pods -o wide


workflows:
  deployment:
    jobs:
      #- build
      #- docker_stuff:
      #    requires: [build]
      #- aws-eks/create-cluster:
      #    cluster-name: forward-thomas-eks-cluster
      #    aws-region: eu-central-1
      #- create_services:
      #    requires: [docker_stuff]     
      #    cluster-name: forward-thomas-eks-cluster
      #    aws-region: eu-central-1              
      - aws-eks/update-container-image:
      #    requires: [create_services]       
          cluster-name: forward-thomas-eks-cluster
          aws-region: eu-central-1
          container-image-updates: helloworldapp=networkingcat/hello_world
          record: true
          resource-name: deployment/helloworldapp          
      - collect_info:
          requires: [aws-eks/update-container-image]
          cluster-name: forward-thomas-eks-cluster
          aws-region: eu-central-1        
   


